# Generated by Django 4.2.3 on 2023-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='images/%Y', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
